deliverables:
- name: "HTML5"
  context:
    input: "../webroot.ditamap"
  publication:
    transtype: "html5-bootstrap"
    params:
    - name: "args.hdr"
      href: "../navbar.xml"
    - name: "args.hdf"
      href: "../fonts.xml"
    - name: "args.css"
      value: "custom.css"
    - name: "args.cssroot"
      path: "../"
